# Generated by Django 5.1.3 on 2024-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerregistry',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=20, verbose_name='Protocol type'),
        ),
    ]
