# Generated by Django 5.1.3 on 2024-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_service', '0002_dockerregistry_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='healthcheck_command',
            field=models.TextField(blank=True, null=True, verbose_name='Healthcheck Command'),
        ),
        migrations.AlterField(
            model_name='container',
            name='interval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Interval'),
        ),
        migrations.AlterField(
            model_name='container',
            name='retries',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Retries'),
        ),
        migrations.AlterField(
            model_name='container',
            name='start_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Start period'),
        ),
        migrations.AlterField(
            model_name='container',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Timeout'),
        ),
        migrations.AlterField(
            model_name='service',
            name='healthcheck_command',
            field=models.TextField(blank=True, null=True, verbose_name='Healthcheck Command'),
        ),
        migrations.AlterField(
            model_name='service',
            name='interval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Interval'),
        ),
        migrations.AlterField(
            model_name='service',
            name='retries',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Retries'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Start period'),
        ),
        migrations.AlterField(
            model_name='service',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Healthcheck Timeout'),
        ),
    ]
