# Generated by Django 5.1.3 on 2024-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_service', '0003_alter_container_healthcheck_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='internal_ip',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Internal IP'),
        ),
    ]
