#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py migrate
python manage.py init_admin
# python manage.py init_site
exec gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload --workers 4
# python manage.py runserver 0.0.0.0:8000
